# Working by itself
#  docker run -it -v $(pwd)/reason-source/src:/usr/app/react-ml/src -v $(pwd)/reason-source/lib:/usr/app/react-ml/lib react-reason sh -c 'yarn start;'
version: '3.2'
services:

  react-ml:
    container_name: react-reason
    # image: react-reason
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./reason-source/src:/usr/app/react-ml/src
      - ./reason-source/lib:/usr/app/react-ml/lib
      - ./reason-source/build:/usr/app/react-ml/build
      - node_modules:/usr/app/react-ml/node_modules
    entrypoint: sh -c "yarn clean && yarn build && yarn start"


  webpack:
    # image: node:9.5.0-alpine
    user: root
    build:
      context: .
      dockerfile: webpack.Dockerfile
    depends_on:
      - react-ml
    container_name: webpack
    volumes:
      - ./reason-source/src:/usr/app/react-ml/src
      # - ./reason-source/lib:/usr/app/react-ml/lib
      - ./reason-source/build:/usr/app/react-ml/build
      # - reason-build:/usr/app/react-ml/build
      - node_modules:/usr/app/react-ml/node_modules
    entrypoint: yarn webpack


  nginx:
    image: nginx:1.14.0-alpine
    container_name: nginx
    ports:
      -  '8080:80'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - ./reason-source/build:/usr/html
      # - static-content:/usr/html
      # - reason-build:/usr/html

    #   - type: bind
    #     source: ./default.conf
    #     target: /etc/nginx/conf.d/default.conf
    #   - type: bind
    #     source: ./reason-source/build
    #     target: /usr/html
    # networks:
    #   - new

# volumes:
#   web_app:
#     driver: local
#     driver_opts:
#       type: none
#       device: $PWD/${WEB_APP_PATH}
#       o: bind

# networks:
#   new:

volumes:
  node_modules:

#docker run --rm --name react -d
#-v $(pwd)/reason-source/src:/usr/app/react-ml/src
#-v $(pwd)/reason-source/build:/usr/app/react-ml/build
# react-reason
# sh -c 'yarn webpack | yarn start'
