# Working by itself
#  docker run -it -v $(pwd)/reason-source/src:/usr/app/react-ml/src -v $(pwd)/reason-source/lib:/usr/app/react-ml/lib react-reason sh -c 'yarn start;'
version: '3.2'
services:

  react-ml:
    container_name: react-reason
    # working_dir: /usr/app/react-ml
    image: react-reason
    volumes:
      # - type: volume
      #   source: mydata
      #   target: /data
      #   volume:
      #     nocopy: true
      - type: mount
        source: ./reason-source/src
        target: /usr/app/react-ml/src

      - type: mount
        source: ./reason-source/lib
        target: /usr/app/react-ml/lib
      # - ./reason-source/src:/usr/app/react-ml/src
      # - ./reason-source/lib:/usr/app/react-ml/lib

    entrypoint: sh -c 'yarn start > ./reason.log 2>&1 & npx webpack -w'
    # entrypoint: sh -c 'yarn start'

      # - './reason-source:/usr/app/react-ml'
      # - static-content:/usr/app/react-ml/build
    # networks:
    #   - new
    # entrypoint: sh -c 'yarn start'
    # entrypoint: sh -c 'cd /usr/app/react-ml;yarn start;'

  # webpack:
  #   image: node:9.5.0-alpine
  #   container_name: webpack
  #   working_dir: /root
  #   volumes:
  #     - './reason-source:/root'
      # - static-content:/usr/app/react-ml/build
    # networks:
    #   - new
    # entrypoint: sh -c 'yarn webpack > ./webpack.log 2>&1'
    # entrypoint: sh -c 'cd /root;yarn;yarn webpack;'

  nginx:
    image: nginx:1.14.0-alpine
    container_name: nginx
    ports:
      -  '8080:80'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      # - static-content:/usr/html
      - './reason-source/build:/usr/html'
      # - type: bind
      #   source: ./default.conf
      #   target: /etc/nginx/conf.d/default.conf
      # - type: bind
      #   source: ./reason-source/build
      #   target: /usr/html
    # networks:
    #   - new

# volumes:
#   web_app:
#     driver: local
#     driver_opts:
#       type: none
#       device: $PWD/${WEB_APP_PATH}
#       o: bind

# networks:
#   new:

# volumes:
#   node-modules:

#docker run --rm --name react -d
#-v $(pwd)/reason-source/src:/usr/app/react-ml/src
#-v $(pwd)/reason-source/build:/usr/app/react-ml/build
# react-reason
# sh -c 'yarn webpack | yarn start'
